theme: jekyll-theme-cayman
title: 不知飞到哪                     #你博客的标题
SEOTitle: 不知飞到哪但还是尽力去费飞        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: 515411330@qq.com    
description: "记录一些心得和趟过的坑"              #网站介绍
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone" #关键词
url: "https://nightelforc.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
